version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      devnet:
        driver: bridge

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devnet

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devnet

  sql-server:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - devnet

  spring-app:
    build:
      context: ./spring-app
    ports:
      - "8082:8080"
    depends_on:
      - sql-server
      - nexus
      - sonarqube
      - jenkins
    networks:
      - devnet

networks:
  my-network:

volumes:
  jenkins_data:
  nexus_data:


  
